configure: add bison quirk

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27,10 +27,10 @@ fatal() {
 }
 
 headers() {
-	cat >"$TMP"
-	[ -s "$TMP" ] || return 0
+	cat >"$TMP1"
+	[ -s "$TMP1" ] || return 0
 
-	xargs printf '#include <%s>\n' <"$TMP"
+	xargs printf '#include <%s>\n' <"$TMP1"
 }
 
 makevar() {
@@ -77,7 +77,7 @@ check_errc() {
 
 # Check if strptime(3) is hidden behind _GNU_SOURCE.
 check_gnu_source() {
-	cat <<-EOF >"$TMP"
+	cat <<-EOF >"$TMP1"
 	#include <time.h>
 
 	int main(void) {
@@ -86,9 +86,9 @@ check_gnu_source() {
 	}
 	EOF
 
-	compile <"$TMP" && return 1
+	compile <"$TMP1" && return 1
 
-	{ echo "#define _GNU_SOURCE"; cat "$TMP"; } | compile
+	{ echo "#define _GNU_SOURCE"; cat "$TMP1"; } | compile
 }
 
 check_host_name_max() {
@@ -188,8 +188,41 @@ check_warnc() {
 	EOF
 }
 
-TMP=$(mktemp -t configure.XXXXXX)
-trap "atexit $TMP" EXIT
+# Quirk for GNU Bison 2.X present on macOS which unconditionally declares
+# YYSTYPE unless YYSTYPE_IS_DECLARED is defined.
+check_yystype() {
+	cat <<-EOF >"$TMP1"
+	%{
+	void yyerror(const char *, ...);
+	int yylex(void);
+
+	typedef double YYSTYPE;
+	%}
+
+	%%
+	grammar:
+	%%
+
+	int main(void) {
+		return 0;
+	}
+
+	void yyerror(const char *fmt, ...)
+	{
+	}
+
+	int yylex(void) {
+		return 0;
+	}
+	EOF
+
+	$YACC -o "$TMP2" "$TMP1" || fatal "${YACC}: fatal error"
+	! compile <"$TMP2"
+}
+
+TMP1=$(mktemp -t configure.XXXXXX)
+TMP2=$(mktemp -t configure.XXXXXX)
+trap "atexit $TMP1 $TMP2" EXIT
 
 exec 3>&1 4>&2
 exec 1>config.log 2>&1
@@ -211,6 +244,7 @@ HAVE_STAT_TIM=0
 HAVE_STRLCPY=0
 HAVE_UTIMENSAT=0
 HAVE_WARNC=0
+HAVE_YYSTYPE=0
 
 # Order is important, must come first if not defined.
 DEBUG="$(makevar DEBUG || :)"
@@ -242,6 +276,7 @@ check_stat_tim && HAVE_STAT_TIM=1
 check_strlcpy && HAVE_STRLCPY=1
 check_utimensat && HAVE_UTIMENSAT=1
 check_warnc && HAVE_WARNC=1
+check_yystype && HAVE_YYSTYPE=1
 
 MALLOC_OPTIONS=$(check_malloc_options)
 
@@ -280,6 +315,10 @@ if [ $HAVE_STAT_TIM -eq 0 ]; then
 fi
 
 [ $HAVE_UTIMENSAT -eq 0 ] && printf '#define UTIME_OMIT\t-1L\n'
+
+if [ $HAVE_YYSTYPE -eq 1 ]; then
+	printf '#define YYSTYPE_IS_DECLARED\t1\n'
+fi
 
 [ $HAVE_ARC4RANDOM -eq 0 ] &&
 	printf 'uint32_t arc4random(void);\n'
