configure: sync

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10,13 +10,14 @@ atexit() {
 	set -x
 	[ -e config.h ] && cat config.h
 	[ -e config.mk ] && cat config.mk
-	rm -f "$@"
+	rm -rf "$@" || :
 	[ "$_err" -ne 0 ] && fatal
 	exit 0
 }
 
 compile() {
-	$CC $CPPFLAGS -Werror -o /dev/null -x c - $@
+	# shellcheck disable=SC2086
+	"$CC" $CPPFLAGS -Werror -o /dev/null -x c - "$@"
 }
 
 cc_has_option() {
@@ -33,13 +34,16 @@ fatal() {
 }
 
 headers() {
-	cat >"$TMP1"
-	[ -s "$TMP1" ] || return 0
+	local _tmp="${WRKDIR}/headers"
 
-	xargs printf '#include <%s>\n' <"$TMP1"
+	cat >"$_tmp"
+	[ -s "$_tmp" ] || return 0
+
+	xargs printf '#include <%s>\n' <"$_tmp"
 }
 
 makevar() {
+	# shellcheck disable=SC2016
 	var="$(printf 'all:\n\t@echo ${%s}\n' "$1" | make -sf -)"
 	if [ -n "$var" ]; then
 		echo "$var"
@@ -110,7 +114,9 @@ check_errc() {
 
 # Check if strptime(3) is hidden behind _GNU_SOURCE.
 check_gnu_source() {
-	cat <<-EOF >"$TMP1"
+	local _tmp="${WRKDIR}/gnu"
+
+	cat <<-EOF >"$_tmp"
 	#include <time.h>
 
 	int main(void) {
@@ -119,9 +125,9 @@ check_gnu_source() {
 	}
 	EOF
 
-	compile <"$TMP1" && return 1
+	compile <"$_tmp" && return 1
 
-	{ echo "#define _GNU_SOURCE"; cat "$TMP1"; } | compile
+	{ echo "#define _GNU_SOURCE"; cat "$_tmp"; } | compile
 }
 
 check_pledge() {
@@ -215,7 +221,10 @@ check_warnc() {
 # Quirk for GNU Bison 2.X present on macOS which declares YYSTYPE unless
 # YYSTYPE_IS_DECLARED is defined.
 check_yystype() {
-	cat <<-EOF >"$TMP1"
+	local _c="${WRKDIR}/c"
+	local _yacc="${WRKDIR}/yacc"
+
+	cat <<-EOF >"$_c"
 	%{
 	void yyerror(const char *, ...);
 	int yylex(void);
@@ -240,8 +249,8 @@ check_yystype() {
 	}
 	EOF
 
-	$YACC -o "$TMP2" "$TMP1" || fatal "${YACC}: fatal error"
-	! compile <"$TMP2"
+	$YACC -o "$_yacc" "$_c" || fatal "${YACC}: fatal error"
+	! compile <"$_yacc"
 }
 
 _pedantic=0
@@ -254,9 +263,8 @@ while [ $# -gt 0 ]; do
 	shift
 done
 
-TMP1=$(mktemp -t configure.XXXXXX)
-TMP2=$(mktemp -t configure.XXXXXX)
-trap "atexit $TMP1 $TMP2" EXIT
+WRKDIR=$(mktemp -dt configure.XXXXXX)
+trap 'atexit $WRKDIR' EXIT
 
 exec 3>&1 4>&2
 exec 1>config.log 2>&1
@@ -286,7 +294,7 @@ CC=$(makevar CC || fatal "CC: not defined")
 CFLAGS="$(unset CFLAGS DEBUG; makevar CFLAGS || :) ${CFLAGS:-} ${DEBUG}"
 CFLAGS="${CFLAGS} -Wall -Wextra -MD -MP"
 CPPFLAGS="$(makevar CPPFLAGS || :)"
-LDFLAGS="$(DEBUG= makevar LDFLAGS || :)"
+LDFLAGS="$(DEBUG='' makevar LDFLAGS || :)"
 YACC=$(makevar YACC || fatal "YACC: not defined")
 YFLAGS="$(makevar YFLAGS || :)"
 
@@ -294,7 +302,7 @@ PREFIX="$(makevar PREFIX || echo /usr/local)"
 BINDIR="$(makevar BINDIR || echo "${PREFIX}/bin")"
 MANDIR="$(makevar MANDIR || echo "${PREFIX}/man")"
 INSTALL="$(makevar INSTALL || echo install)"
-INSTALL_MAN="$(makevar INSTALL_MAN || echo install)"
+INSTALL_MAN="$(makevar INSTALL_MAN || echo "$INSTALL")"
 
 # Following chunks must happen after CC is defined.
 if [ "$_pedantic" = 1 ]; then
@@ -321,58 +329,58 @@ check_yystype && HAVE_YYSTYPE=1
 exec 1>config.h
 
 # Order is important, must be present before any includes.
-[ $HAVE_GNU_SOURCE -eq 1 ] && printf '#define _GNU_SOURCE\n'
+[ "$HAVE_GNU_SOURCE" -eq 1 ] && printf '#define _GNU_SOURCE\n'
 
 # Headers needed for function prototypes.
 {
-[ $HAVE_ARC4RANDOM -eq 0 ] && echo stdint.h
-[ $HAVE_PLEDGE -eq 0 ] && echo stdlib.h
-[ $HAVE_REALLOCARRAY -eq 0 ] && echo stdlib.h
-[ $HAVE_STRLCPY -eq 0 ] && echo stdlib.h
-[ $HAVE_UTIMENSAT -eq 0 ] && echo sys/time.h
+[ "$HAVE_ARC4RANDOM" -eq 0 ] && echo stdint.h
+[ "$HAVE_PLEDGE" -eq 0 ] && echo stdlib.h
+[ "$HAVE_REALLOCARRAY" -eq 0 ] && echo stdlib.h
+[ "$HAVE_STRLCPY" -eq 0 ] && echo stdlib.h
+[ "$HAVE_UTIMENSAT" -eq 0 ] && echo sys/time.h
 } | sort | uniq | headers
 
-[ $HAVE_ARC4RANDOM -eq 1 ] && printf '#define HAVE_ARC4RANDOM\t1\n'
-[ $HAVE_ERRC -eq 1 ] && printf '#define HAVE_ERRC\t1\n'
-[ $HAVE_PLEDGE -eq 1 ] && printf '#define HAVE_PLEDGE\t1\n'
-[ $HAVE_QUEUE -eq 1 ] && printf '#define HAVE_QUEUE\t1\n'
-[ $HAVE_REALLOCARRAY -eq 1 ] && printf '#define HAVE_REALLOCARRAY\t1\n'
-[ $HAVE_STRLCPY -eq 1 ] && printf '#define HAVE_STRLCPY\t1\n'
-[ $HAVE_UTIMENSAT -eq 1 ] && printf '#define HAVE_UTIMENSAT\t1\n'
-[ $HAVE_WARNC -eq 1 ] && printf '#define HAVE_WARNC\t1\n'
+[ "$HAVE_ARC4RANDOM" -eq 1 ] && printf '#define HAVE_ARC4RANDOM\t1\n'
+[ "$HAVE_ERRC" -eq 1 ] && printf '#define HAVE_ERRC\t1\n'
+[ "$HAVE_PLEDGE" -eq 1 ] && printf '#define HAVE_PLEDGE\t1\n'
+[ "$HAVE_QUEUE" -eq 1 ] && printf '#define HAVE_QUEUE\t1\n'
+[ "$HAVE_REALLOCARRAY" -eq 1 ] && printf '#define HAVE_REALLOCARRAY\t1\n'
+[ "$HAVE_STRLCPY" -eq 1 ] && printf '#define HAVE_STRLCPY\t1\n'
+[ "$HAVE_UTIMENSAT" -eq 1 ] && printf '#define HAVE_UTIMENSAT\t1\n'
+[ "$HAVE_WARNC" -eq 1 ] && printf '#define HAVE_WARNC\t1\n'
 
-if [ $HAVE_ATTRIBUTE_FALLTHROUGH -eq 1 ]; then
+if [ "$HAVE_ATTRIBUTE_FALLTHROUGH" -eq 1 ]; then
 	printf '#define FALLTHROUGH __attribute__((__fallthrough__))\n'
 else
 	printf '#define FALLTHROUGH do {} while (0) /* FALLTHROUGH */\n'
 fi
 
-if [ $HAVE_STAT_TIM -eq 0 ]; then
+if [ "$HAVE_STAT_TIM" -eq 0 ]; then
 	printf '#define st_atim\tst_atimespec\n'
 	printf '#define st_ctim\tst_ctimespec\n'
 	printf '#define st_mtim\tst_mtimespec\n'
 fi
 
-[ $HAVE_UTIMENSAT -eq 0 ] && printf '#define UTIME_OMIT\t-1L\n'
+[ "$HAVE_UTIMENSAT" -eq 0 ] && printf '#define UTIME_OMIT\t-1L\n'
 
-if [ $HAVE_YYSTYPE -eq 1 ]; then
+if [ "$HAVE_YYSTYPE" -eq 1 ]; then
 	printf '#define YYSTYPE_IS_DECLARED\t1\n'
 fi
 
-[ $HAVE_ARC4RANDOM -eq 0 ] &&
+[ "$HAVE_ARC4RANDOM" -eq 0 ] &&
 	printf 'uint32_t arc4random(void);\n'
-[ $HAVE_ERRC -eq 0 ] && {
+[ "$HAVE_ERRC" -eq 0 ] && {
 	printf 'void errc(int, int, const char *, ...)\n';
 	printf '\t__attribute__((__noreturn__, __format__ (printf, 3, 4)));\n'; }
-[ $HAVE_PLEDGE -eq 0 ] &&
+[ "$HAVE_PLEDGE" -eq 0 ] &&
 	printf 'int pledge(const char *, const char *);\n'
-[ $HAVE_REALLOCARRAY -eq 0 ] &&
+[ "$HAVE_REALLOCARRAY" -eq 0 ] &&
 	printf 'void *reallocarray(void *, size_t, size_t);\n'
-[ $HAVE_STRLCPY -eq 0 ] &&
+[ "$HAVE_STRLCPY" -eq 0 ] &&
 	printf 'size_t strlcpy(char *, const char *, size_t);\n'
-[ $HAVE_UTIMENSAT -eq 0 ] &&
+[ "$HAVE_UTIMENSAT" -eq 0 ] &&
 	printf 'int utimensat(int, const char *, const struct timespec [2], int);\n'
-[ $HAVE_WARNC -eq 0 ] && {
+[ "$HAVE_WARNC" -eq 0 ] && {
 	printf 'void warnc(int, const char *, ...)\n'
 	printf '\t__attribute__((__format__ (printf, 2, 3)));\n'; }
 
@@ -380,6 +388,7 @@ fi
 exec 1>config.mk
 
 # Use echo to normalize whitespace.
+# shellcheck disable=all
 cat <<EOF
 CC=		$(echo $CC)
 CFLAGS=		$(rmdup $CFLAGS)
@@ -392,7 +401,7 @@ YFLAGS=		$(rmdup $YFLAGS)
 BINDIR?=	$(echo $BINDIR)
 MANDIR?=	$(echo $MANDIR)
 INSTALL?=	$(echo $INSTALL)
-INSTALL_MAN?=	\${INSTALL}
+INSTALL_MAN?=	$(echo $INSTALL_MAN)
 
 .PATH:	\${.CURDIR}/libks
 VPATH=	\${.CURDIR}/libks
